[package]
name = "hazedumper"
version = "2.4.1"
authors = ["frk <hazefrk+dev@gmail.com>"]
build = "build.rs"

[package.metadata.winres]
ProductName = "HazeDumper"
CompanyName = "Haze-Productions"
OriginalFilename = "hazedumper.exe"
LegalCopyright = "MIT-License"

[dependencies]
serde = "1.0.71"
serde_json = "1.0.24"
serde_derive = "1.0.71"
structopt = "0.2.10"
structopt-derive = "0.2.10"
winapi = "0.3.5"
log = "0.4.3"
simplelog = "0.5.2"
failure = "0.1.2"
regex = "1.0.2"
chrono = { version = "0.4.5", features = ["serde"] }
serde_yaml = "0.7.5"
toml = "0.4.6"
nom = "4.0.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.5", features = ["basetsd","handleapi","memoryapi","minwindef","ntdef","processthreadsapi","tlhelp32","winnt", "wow64apiset"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.6"
