[package]
name = "hazedumper"
version = "2.4.1"
authors = ["frk <hazefrk+dev@gmail.com>"]
build = "build.rs"
edition = "2018"

[package.metadata.winres]
ProductName = "HazeDumper"
CompanyName = "Haze-Productions"
OriginalFilename = "hazedumper.exe"
LegalCopyright = "MIT-License"

[dependencies]
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
structopt = "0.2.13"
structopt-derive = "0.2.13"
winapi = "0.3.6"
log = "0.4.6"
simplelog = "0.5.3"
failure = "0.1.3"
regex = "1.1.0"
chrono = { version = "0.4.6", features = ["serde"] }
serde_yaml = "0.8.8"
toml = "0.4.10"
nom = "4.1.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.6", features = ["basetsd","handleapi","memoryapi","minwindef","ntdef","processthreadsapi","tlhelp32","winnt", "wow64apiset"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.8"
